---
Name: 'dd-tawkto'
After:
- '*'
---
PageController:
  extensions:
  - DorsetDigital\TawkTo\PageControllerExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
  - DorsetDigital\TawkTo\SiteConfigExtension